apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-api
  labels:
    app: incident-api
    version: "0.4.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-api
  template:
    metadata:
      labels:
        app: incident-api
    spec:
      containers:
        - name: incident-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: soc-triager-secrets
                  key: jwt-secret
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: soc-triager-secrets
                  key: anthropic-api-key
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: soc-triager-secrets
                  key: postgres-url
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
