"""
Markdown incident report generator.
Uses Jinja2 to produce a structured Markdown report from an incident dict.
All raw log content is sanitized via sanitize_log_content() before rendering.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from jinja2 import Environment, BaseLoader

from backend.artifacts.sanitizers import sanitize_log_content

REPORT_TEMPLATE = """\
# Incident Report: {{ incident.title }}

**Severity:** {{ incident.severity | upper }}  
**Status:** {{ incident.status }}  
**Generated:** {{ generated_at }}  
**Incident ID:** `{{ incident.id }}`  

---

## Executive Summary

{{ incident.llm_rationale }}

**MITRE ATT&CK:** `{{ incident.technique_id }}` — {{ incident.technique_name }} ({{ incident.tactic }})  
**Confidence:** {{ (incident.confidence * 100) | round(0) | int }}%  
**Recommended Action:** {{ incident.recommended_action }}

---

## Timeline of Events

| Time | Event | Source |
|---|---|---|
{% for alert_id in incident.alerts -%}
| {{ incident.created_at }} | Alert `{{ alert_id }}` triggered | Pipeline |
{% endfor %}

---

## Entities Involved

{% for entity in incident.entities -%}
- **{{ entity.role | capitalize }}:** 
  {%- if entity.ip %} IP `{{ entity.ip }}`{% endif %}
  {%- if entity.host %} Host `{{ entity.host }}`{% endif %}
  {%- if entity.user %} User `{{ entity.user }}`{% endif %}
  {%- if entity.geo_country %} ({{ entity.geo_country }}){% endif %}
{% endfor %}

---

## Evidence Excerpts

```
{{ evidence_excerpt }}
```

---

## MITRE ATT&CK Details

| Field | Value |
|---|---|
| Technique ID | `{{ incident.technique_id }}` |
| Technique Name | {{ incident.technique_name }} |
| Tactic | {{ incident.tactic }} |
| Confidence | {{ (incident.confidence * 100) | round(0) | int }}% |

{{ incident.get('mitre_description', '') }}

---

## Containment Recommendation

> ⚠️ **DRAFT ONLY** — requires Approver authorization before any action is taken.

{{ incident.recommended_action }}

---

*Report generated by SOC Triager v0.4.0. All automated analysis requires human review.*
"""


_jinja_env = Environment(loader=BaseLoader(), autoescape=False)
_template = _jinja_env.from_string(REPORT_TEMPLATE)


def generate_incident_report(incident: dict[str, Any]) -> str:
    """
    Generate a Markdown incident report from an incident dict.
    Returns the rendered Markdown string.
    """
    # Sanitize any log-derived evidence for safe embedding
    raw_logs = incident.get("raw_evidence", [])
    evidence_lines = [sanitize_log_content(line) for line in raw_logs[:5]]
    evidence_excerpt = "\n".join(evidence_lines) if evidence_lines else "No raw evidence captured."

    return _template.render(
        incident=incident,
        evidence_excerpt=evidence_excerpt,
        generated_at=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
    )
